name: "Go Coverage Diff Action"
description: "Show coverage difference between branches in a pull request"
author: "Panagiotis Petridis"
inputs:
  path:
    description: "path to git repo"
    default: "."
  coverprofile:
    description: "path to coverprofile"
  diff:
    description: "path to diff file"
  module:
    description: "the Go module name"
  ignore-main:
    default: "true"
    description: "ignore main package"
  ignore-empty:
    default: "false"
    description: "ignore empty lines"
outputs:
  covdiff:
    description: "the coverage difference (0-100)"
runs:
  using: "docker"
  image: "Dockerfile"
