name: "Go Coverage Diff Action"
description: "Show coverage difference between branches in a pull request"
author: "Panagiotis Petridis"
inputs:
  myInput:
    description: "Input to use"
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
