name: Integration Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: self test
        id: selftest
        uses: panagiotisptr/cov-diff@main
        with:
          myInput: universe

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello universe"
