name: Integration Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run tests
        run: |
          go test ./... -coverprofile=coverage.out

      - name: self test
        id: selftest
        uses: panagiotisptr/cov-diff@main
        with:
          path: .
          coverprofile: coverage.out
          source: ${{ github.ref }}
          target: ${{ github.base_ref }}
          module: github.com/panagiotisptr/cov-diff

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello universe"
